//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crud_Operation_Rest_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CodeRower
    {
        public int configid { get; set; }
        public string configname { get; set; }
    }
}
